name: Deploy staging on push

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Check out, and set up the node/ruby infra
    - uses: ./.github/actions/build-website

    # Get all the local deps
    - run: yarn install
    - run: ( cd src/play && yarn install && yarn setup )
    - run: bundle install

    # Build
    - run: gulp publish

    # Deploy to the staging branch
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v1.1.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PUBLISH_BRANCH: SITE-STAGING
        PUBLISH_DIR: ./site
